### ISSUE TITLE
Banners for OBU Ads

### ISSUE THREAD

**Issue by JorgeEuroWag** [JorgeEuroWag/Eurowagdigital#66]
------
Hi Simone,

Hope all is well.

Here is the main shared-task I require your help with…

Regarding the upcoming OBU Launch -  which at this point is becoming our #1 priority – we need your help on the following:

- 3 Facebook banners for Lead conversions regarding OBU (so basically two different banners which will be used for Facebook Ads about the OBU, image of OBU plus some text, these banners will lead to a press release most likely, so general OBU)

(For each banner please use different image and different text / tagline)

- 2 Facebook banners for EETS Webinar invites regarding OBU (two different banners about EETS which will be used for Webinar promotions, when people click on these it will lead them to a webinar registration page.

(For each banner please use different image and different text / tagline)

I have also uploaded this task on our waffle board, feel free to ask back any questions and I believe the due date for this is actually ASAP -  we are a little bit behind on this initiative so at your earliest convenience will be well appreciated 

Thanks

Jorge	
------

**Comment by simprev** [comment]
First three banners.

I am mooving to complete  the webinar banners
